### PR TITLE
Add workflows

### PR DESCRIPTION
**Pull request by jeanconn**
### Description

Add workflows and other template files.

### Testing

Plan is to verify that a conda package is built and put in masters when this is merged.

### CODE REVIEW

**Comment by taldcroft** [comment]
From what I can see this looks fine, but I'm not sure about the plan for testing the build-related workflows. For those workflows I have no idea if they are OK.

**Comment by jeanconn** [comment]
I don't think it either works or it doesn't but https://github.com/sot/skare3/pull/1139 surely needs to go first for builds to happen.

**Comment by jeanconn** [comment]
I don't know how much of a process to make for testing.  I figured we just merged, see if we got some conda packages, and then decided if we used them or not to do this install.

**Comment by jeanconn** [comment]
Good idea.  Though at this point.  That should probably also go in skare3 in the templates (from which I copied these).

**Comment by jeanconn** [comment]
The build on the merge of this seems to have worked.  I suppose next step would be to cut a release.  What version should that be?

**Pull request merged**
